name: iOS Tests
on:
  pull_request:
    types: [labeled, synchronize]

jobs:
  ios-test:
    if: contains(github.event.pull_request.labels.*.name, 'ios')
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21
      - uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew iosSimulatorArm64Test
